// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package testqueries

import (
	"context"
)

const CustomersCreate = `-- name: CustomersCreate :execrows
INSERT INTO ` + "`" + `customer` + "`" + ` (` + "`" + `id` + "`" + `, ` + "`" + `created_at` + "`" + `) VALUES (?, DEFAULT)
`

// CustomersCreate
//
//	INSERT INTO `customer` (`id`, `created_at`) VALUES (?, DEFAULT)
func (q *Queries) CustomersCreate(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, CustomersCreate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
