version: "3"

services:
  mysql:
    container_name: "mysql-dev"
    network_mode: bridge
    build:
      dockerfile: ./Dockerfile
      context: ./vendor/mysql
      args:
        MYSQL_VERSION: "8.3.0"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "dev"
      MYSQL_PASSWORD: "password"
      MYSQL_USER: "rootuser"
    ports:
      - "3306:3306"

  redis:
    container_name: "redis-dev"
    network_mode: bridge
    image: docker.io/redis:7.2.1-alpine3.18
    command: ["--port", "6379", "--loglevel", "debug"]
    ports:
      - "6379:6379"

  redis-cluster-flow:
    container_name: "redis-cluster-flow-dev"
    network_mode: bridge
    build:
      dockerfile: ./Dockerfile
      context: ./vendor/redis-cluster
    environment:
      START_PORT: 7001
      END_PORT: 7006
    ports:
      - "7001-7006:7001-7006"

  redis-cluster-eth:
    container_name: "redis-cluster-eth-dev"
    network_mode: bridge
    build:
      dockerfile: ./Dockerfile
      context: ./vendor/redis-cluster
    environment:
      START_PORT: 8001
      END_PORT: 8006
    ports:
      - "8001-8006:8001-8006"
