version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:8.2.0
    command: mysqld --general-log=1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "dev"
      MYSQL_USER: "rootuser"
      MYSQL_PASSWORD: "password"
    networks:
      - block_feed_net

  db-ui:
    container_name: cloudbeaver
    image: dbeaver/cloudbeaver:23.2.4
    ports:
      - "8978:8978"
    volumes:
      - ./docker/cloudbeaver/data-sources.json:/opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
    environment:
      CB_SERVER_NAME: dev
      CB_SERVER_URL: http://host.docker.internal:8978
      CB_ADMIN_NAME: rootuser
      CB_ADMIN_PASSWORD: password
    networks:
      - block_feed_net

  # flow_emulator:
  #   container_name: flow-emulator
  #   ports:
  #     - "8888:8888"
  #   build:
  #     dockerfile: ./docker/blockchains/flow/Dockerfile
  #     context: .
  #   networks:
  #     - block_feed_net

  # https://docs.bullmq.io/guide/going-to-production#max-memory-policy
  redis:
    container_name: redis
    image: redis:7.2.1-alpine3.18
    command:
      [
        "redis-server",
        "--port",
        "6379",
        "--loglevel",
        "debug",
        "--maxmemory-policy",
        "noeviction",
      ]
    ports:
      - "6379:6379"
    networks:
      - block_feed_net

networks:
  block_feed_net:
