version: "3"

services:
  block-fetcher-flow-mainnet:
    container_name: block-fetcher-flow-mainnet
    image: caffeineaddict333/block-feed-block-gateway-fetcher-flow:${IMAGE_TAG}
    restart: always
    environment:
      BLOCK_FETCHER_REDIS_URL: ${REDIS_URL}
      ONFLOW_ACCESS_API_URL: https://rest-mainnet.onflow.org
    depends_on:
      - block-consumer
      - block-divider
      - block-logger
    deploy:
      replicas: 1
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  block-divider:
    container_name: block-divider
    image: caffeineaddict333/block-feed-block-gateway-divider:${IMAGE_TAG}
    restart: always
    environment:
      BLOCK_DIVIDER_REDIS_URL: ${REDIS_URL}
      BLOCK_DIVIDER_DB_URL: ${DB_URL}
    deploy:
      replicas: 1
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  block-consumer:
    container_name: block-consumer
    image: caffeineaddict333/block-feed-block-gateway-consumer:${IMAGE_TAG}
    restart: always
    environment:
      BLOCK_CONSUMER_REDIS_URL: ${REDIS_URL}
      BLOCK_CONSUMER_DB_URL: ${DB_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    deploy:
      replicas: 1
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  block-logger:
    container_name: block-logger
    image: caffeineaddict333/block-feed-block-gateway-logger:${IMAGE_TAG}
    restart: always
    environment:
      BLOCK_LOGGER_REDIS_URL: ${REDIS_URL}
      BLOCK_LOGGER_DB_URL: ${DB_URL}
    deploy:
      replicas: 1
    logging:
      options:
        max-size: "10m"
        max-file: "3"
