export const enum JobNames {
  CONSUME_BLOCK = "CONSUME_BLOCK",
  DIVIDE_BLOCK = "DIVIDE_BLOCK",
  FETCH_BLOCK = "FETCH_BLOCK",
  MAIL_BLOCK = "MAIL_BLOCK",
  POST_BLOCK = "POST_BLOCK",
  LOG_BLOCK = "LOG_BLOCK",
}
