export const enum QueueNames {
  BLOCK_CONSUMER = "BLOCK_CONSUMER",
  BLOCK_WEBHOOK = "BLOCK_WEBHOOK",
  BLOCK_DIVIDER = "BLOCK_DIVIDER",
  BLOCK_FETCHER = "BLOCK_FETCHER",
  BLOCK_MAILER = "BLOCK_MAILER",
  BLOCK_LOGGER = "BLOCK_LOGGER",
}
