export const enum GraphQLErrorCode {
  // Conventional error codes
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  BAD_REQUEST = "BAD_REQUEST",

  // Custom errors
  INVALID_SUBSCRIPTION_ERROR = "INVALID_SUBSCRIPTION",
  NOT_SUBSCRIBED_ERROR = "NOT_SUBSCRIBED",
}
