query Webhooks(
  $filters: WebhookFiltersInput!
  $pagination: CursorPaginationInput!
) {
  webhooks(filters: $filters, pagination: $pagination) {
    payload {
      id
      createdAt
      url
      customerId
      blockchainId
      isActive
      maxBlocks
      maxRetries
      timeoutMs
    }
    pagination {
      hasNext
      hasPrev
    }
  }
}
