version: "3"

# TODO: tests should be run using testcontainer: https://node.testcontainers.org/quickstart/

services:
  mysql:
    container_name: mysql
    image: docker.io/mysql:8.2.0
    command: mysqld --general-log=1
    ports:
      - "3306:3306"
    environment:
      # NOTE: the username for the root password is "root"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "dev"
      MYSQL_USER: "rootuser"
      MYSQL_PASSWORD: "password"

  db-ui:
    container_name: cloudbeaver
    image: docker.io/dbeaver/cloudbeaver:23.2.4
    ports:
      - "8978:8978"
    volumes:
      - ./cloudbeaver.data-sources.json:/opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
    environment:
      CB_SERVER_NAME: dev
      CB_SERVER_URL: http://host.docker.internal:8978
      CB_ADMIN_NAME: rootuser
      CB_ADMIN_PASSWORD: password
