on:
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Deploy
        run: |
          cd api && npm install && npm run api:deploy

