on:
  workflow_dispatch:

jobs:
  deploy-block-gateway:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # https://stackoverflow.com/a/58886352/22520608
      # https://stackoverflow.com/a/57969570/22520608
      - name: Export branch, commit hash, and image tag
        run: |
          GIT_COMMIT_BRANCH=${GITHUB_REF#refs/heads/}
          GIT_COMMIT_HASH=$(git rev-parse --short $GITHUB_SHA)
          echo "GIT_COMMIT_BRANCH=$GIT_COMMIT_BRANCH" >> $GITHUB_ENV
          echo "GIT_COMMIT_HASH=$GIT_COMMIT_HASH" >> $GITHUB_ENV
          echo "IMAGE_TAG=$GIT_COMMIT_BRANCH.$GIT_COMMIT_HASH" >> $GITHUB_ENV

      - name: Build code
        run: |
          cd api && npm install && npm run block:build -- production

      - name: Push docker images to dockerhub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          cd api && npm run block:push -- \
            --dockerhub-uname "$DOCKERHUB_USERNAME" \
            --dockerhub-pword "$DOCKERHUB_PASSWORD" \
            --image-tag "$IMAGE_TAG"

      # TODO: ENVIRONMENT is not defined
      - name: Deploy
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_KEY }}
        run: |
          cd api && npm run block:deploy -- \
            --environment "$ENVIRONMENT" \
            --image-tag "$IMAGE_TAG"
